# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2023 Intel Corporation

apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 2
  template:
    metadata:
      labels:
        control-plane: controller-manager
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              control-plane: controller-manager
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        name: manager
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
              drop:
                - all
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: ETHERNET_NODE_LABEL
          value: "ethernet.intel.com/intel-ethernet-present"
        - name: ETHERNET_NODE_LABELER_IMAGE
          value: $ETHERNET_NODE_LABELER_IMAGE
        - name: ETHERNET_DAEMON_IMAGE
          value: $ETHERNET_DAEMON_IMAGE
        - name: ETHERNET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOK_MTLS
          valueFrom:
            configMapKeyRef:
              name: webhook-config
              key: enable-webhook-mtls
              optional: true
        volumeMounts:
          - name: webhook-ca
            mountPath: /etc/ieo-webhook/pki/
      volumes:
        - name: webhook-ca
          secret:
            secretName: webhook-client-ca
            optional: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
