# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2023 Intel Corporation

---
apiVersion: flowconfig.intel.com/v1
kind: FlowConfigNodeAgentDeployment
metadata:
  labels:
    control-plane: flowconfig-daemon
  name: flowconfignodeagentdeployment-sample
  namespace: intel-ethernet-operator
spec:
  DCFVfPoolName: intel.com/cvl_uft_admin
  NADAnnotation: flowconfig-daemon-sriov-cvl0-admin
